@startuml architecture

entity Product {
    + id: Integer
    + name: String
    + description: String
    + category: String
    + price: Integer
    + cost: Integer
    + stock: Integer
    + clothing_size: Integer
    + shoe_size: Integer
    + company_name: String
}

entity Company {
    + name: String
    + capital: Integer
    + income: Integer
    + costs: Integer
    + is_discount_enabled: Boolean
}

Product }|--|| Company : "company_name"

@enduml